---
title: "2021 Draft Results Analysis"
author: "Tom Kain"
date: "8/23/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(paste(getwd(), "_libraries.R", sep = "/"))
```

```{r import_export}
#TODO fix players with NA points (bad join)

draft_results <-
  here::here("in", "2021_draft_results.htm") %>% 
  draft_results_html_to_table() %>%
  rename(bid = salary) %>% 
  mutate(position = if_else(position == "DEF","DST",position),
         team = case_when(
           team == "NO" ~ "NOS",
           team == "GB" ~ "GBP",
           team == "KC" ~ "KCC",
           team == "LV" ~ "LVR",
           team == "TB" ~ "TBB",
           team == "SF" ~ "SFO",
           team == "NE" ~ "NEP",
           team == "JAX" ~ "JAC",
           TRUE ~ team),
         player = gsub(" Jr.", "", player),
         player = gsub(" III", "", player),
         player = gsub(" II", "", player))

draft_with_projections <-
  here::here("in", "projections-2021-08-21.csv") %>% 
  read_csv(show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  mutate(yahoo_value = pmax(league_value, proj_salary, avg_salary) %>% round,
         yahoo_value = if_else(is.na(yahoo_value), 0, yahoo_value),
         full_name = if_else(position == 'DST',
                             first_name,
                             paste0(first_name, " ", last_name))) %>% 
  select(first_name:position, full_name, points_per_game, risk, vorp, max_bid, yahoo_value) %>% 
  right_join(draft_results,
            by = c("full_name" = "player", "position" = "position", "team" = "team")) %>% 
  select(pick, full_name, team, position, points_per_game, vorp, risk, yahoo_value, max_bid, bid, fantasy_team) %>% 
  group_by(fantasy_team, position) %>% 
  mutate(team_pos_rank = rank(-points_per_game, ties.method = "first")) %>% 
  ungroup()


```

```{r starting_vorp_per_team}

draft_analysis <- 
  draft_with_projections %>% 
  identify_starters_by_ppg() %>% 
  select(fantasy_team, pick, full_name, slot, points_per_game, vorp, risk, bid, max_bid, yahoo_value) %>% 
  arrange(fantasy_team, pick)

draft_analysis %>% 
  group_by(fantasy_team) %>% 
  summarize(across(c(points_per_game, vorp), sum, na.rm=TRUE),
            players = n()) %>% 
  arrange(-points_per_game)

```

```{r export}

here::here("out", "draft_results_with_projections.csv") %>% 
  write_csv(draft_with_projections, .)

here::here("out", "draft_analysis_starters_by_ppg.csv") %>% 
  write_csv(draft_analysis, .)

```