---
title: "Fantasy Football Draft Prep"
author: "Tom Kain"
date: "8/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(paste(getwd(), "_libraries.R", sep = "/"))
```

```{r constants}
# TODO identify early easy opponent defenses
# TODO identify sleepers/penny stocks

# TODO retrieve replacement values from last year

# TODO export best/replacement values by position, last year actual and this year projected

season <- 2022
regular_season_games <- 17
budget <- 200
target_points_week <- 131.7 #average winning score in 2021
dollar_vorp_target_override <- 7.46 #from budget / (130 - manually computed replacement values from 2019)

out <- here::here("out")
latest <- here::here(out, "latest")

google_sheet_url <- 
  config::get(file = here::here("conf", "conf.yaml"))$google$gsheet_url
```

```{r scrape_projections}
scrape_file <- 
  here::here(out, paste0("scrape-", Sys.Date(), ".Rds"))

if (file.exists(scrape_file)) {
  scrape <- readRDS(scrape_file)
} else {
  scrape <- 
    scrape_data(src = c(
      "CBS", "ESPN", "Yahoo", "NFL", "FantasyPros", "NumberFire", 
      "FFToday", "FantasySharks", "FantasyFootballNerd", 
      "Walterfootball", "RTSports", "FantasyData", "Fleaflicker"), 
      pos = c("QB", "RB", "WR", "TE", "DST", "K"),
      season = season, 
      week = 0)
  
  write_rds(scrape, 
            scrape_file)
  
  write_rds(scrape, 
            here::here(latest, "scrape-latest.Rds"))
}
```

```{r scrape_yahoo_auction_values}

yahoo_av_file <-
  here::here(out, paste0("yahoo-av-", Sys.Date(), ".csv"))

if (file.exists(yahoo_av_file)) {
  yahoo_av <- 
    read_csv(yahoo_av_file, show_col_types = FALSE)
} else {
  yahoo_av <- 
    scrape_predraft_ranking_pages() %>% 
    mutate(position = if_else(position == "DEF","DST",position),
           team = case_when(
             team == "NO" ~ "NOS",
             team == "GB" ~ "GBP",
             team == "KC" ~ "KCC",
             team == "LV" ~ "LVR",
             team == "TB" ~ "TBB",
             team == "SF" ~ "SFO",
             team == "NE" ~ "NEP",
             TRUE ~ team),
           player = gsub(" Jr.", "", player),
           player = gsub(" III", "", player),
           player = gsub(" II", "", player))
  
  write_csv(yahoo_av, yahoo_av_file)
  write_csv(yahoo_av, here::here(latest, "yahoo-av-latest.csv"))
}
```

```{r dst_yardage_model}
def_perf_file <-
  here::here(out, paste0("def_perf_file-", season, ".csv"))

if (file.exists(def_perf_file)) {
  def_perf <- 
    read_csv(def_perf_file, show_col_types = FALSE)
} else {
  pbp <- nflfastR::load_pbp(c(season-6):(season-1))

  def_perf <-
    pbp %>% 
    filter(!is.na(yards_gained)) %>% 
    filter(!is.na(defteam)) %>% 
    group_by(defteam, game_id, week, game_date) %>% 
    summarize(yards_allowed = sum(yards_gained)) %>% 
    arrange(game_date, game_id)
  
  rm(pbp)
  nflreadr::.clear_cache()
  
  write_csv(def_perf, def_perf_file)
  write_csv(def_perf, here::here(latest, "def-perf-latest.csv"))
}

dst_yardage_points <-
  def_perf %>%
  rename(yards = yards_allowed,
         team = defteam) %>% 
  filter(!is.na(yards)) %>% 
  mutate(year = substr(game_date, 0, 4)) %>% 
  mutate(points = case_when(
    yards < 100 ~ 11.5,
    yards < 200 ~ 9.5,
    yards < 300 ~ 8.5,
    yards < 400 ~ 6,
    yards < 500 ~ 2.5,
    TRUE ~ 0)) %>% 
  group_by(year, team) %>% 
  summarize(weeks = n(),
            yards = sum(yards),
            points = sum(points),
            points_per_week = points / weeks,
            yards_per_week = yards / weeks)
  
model <- lm(points_per_week ~ yards_per_week,
            data=dst_yardage_points)

predicted_yards_per_game <- 
  scrape$DST %>% 
  mutate(id = if_else(
    is.na(id) & startsWith(player, "Las Vegas"),
    "0513", id)) %>% 
  filter(!is.na(dst_yds_allowed)) %>% 
  group_by(id) %>% 
  summarize(yards_per_week = mean(dst_yds_allowed) / regular_season_games)

predicted_yards_per_game$points_per_week <- 
  predict(model, predicted_yards_per_game)

predicted_yards_per_game <-
  predicted_yards_per_game %>% 
  mutate(additional_points = (points_per_week * regular_season_games) %>% round()) %>% 
  select(id, additional_points)
```

```{r projection_table}
projections_table_file <- 
  here::here(out, paste0("projections_table-", Sys.Date(), ".Rds"))

if (file.exists(projections_table_file)) {
  projections_table <- readRDS(projections_table_file)
} else {
  projections_table <- 
    projections_table(scrape,
                      scoring_rules = scoring_rules()) %>% 
    add_ecr() %>% 
    add_risk() %>%
    add_adp() %>% 
    add_aav_custom() %>% 
    add_player_info()
  
  write_rds(projections_table, 
            projections_table_file)
  
  write_rds(projections_table, 
            here::here(latest, "projections_table-latest.Rds"))
}
```

```{r projections}
projections <-
  projections_table %>%
  filter(position != 'LB') %>% 
  select(id:position, avg_type:ceiling, tier:aav) %>% 
  group_by(id, first_name, last_name, team, position) %>% 
  summarize(points = mean(points) %>% round(),
            sd_pts = mean(sd_pts) %>% round(),
            tier = min(tier),
            points_vor = mean(points_vor) %>% round(),
            floor_vor = min(floor_vor) %>% round(),
            ceiling_vor = max(ceiling_vor) %>% round(),
            pos_ecr = mean(pos_ecr) %>% round(),
            sd_ecr = mean(sd_ecr) %>% round(),
            risk = mean(risk) %>% round(),
            adp = mean(adp) %>% round(),
            aav = max(1, mean(aav) %>% round())) %>% 
  left_join(predicted_yards_per_game, by = "id") %>%
  rename(points_adjustment = additional_points) %>% 
  group_by(position) %>% 
  mutate(
    points_adjustment = if_else(
      is.na(points_adjustment), 
      0, points_adjustment),
    points = if_else(
      is.na(points_adjustment), points,
      points + points_adjustment),
    pos_rank = rank(-points, ties.method="min")) %>% 
  ungroup() %>% 
  mutate(rank = rank(-points, ties.method="min"),
         points_per_game = (points / regular_season_games) %>% round(1),
         flex = if_else(position %in% c('RB','WR','TE'), TRUE, FALSE)) %>% 
  group_by(flex) %>% 
  mutate(flex_rank = rank(-points, ties.method="min")) %>% 
  ungroup() %>% 
  mutate(flex_rank = ifelse(flex, flex_rank, NA)) %>% 
  vorp_auction(target_points_week = target_points_week,
               budget = budget,
               dollar_vorp_target_override = dollar_vorp_target_override) %>% 
  select(id:sd_pts, 
         points_per_game, 
         tier, 
         pos_tier, 
         pos_ecr:rank, 
         flex_rank:max_bid) %>% 
  mutate(full_name = if_else(position == 'DST',
                             first_name,
                             paste0(first_name, " ", last_name))) %>% 
  left_join(yahoo_av, 
            by = c("full_name" = "player", "position" = "position", "team" = "team")) %>% 
  select(-full_name)

write_csv(projections, 
          here::here(out, paste0("projections-", Sys.Date(), ".csv")))

write_csv(projections, 
          here::here(latest, "projections-latest.csv"))
```

```{r}
projections %>% 
  googlesheets4::write_sheet(google_sheet_url,sheet = "projections")
```