---
title: "POC"
author: "Tom Kain"
date: "8/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ffanalytics")
library("here")
library("readr")
library("janitor")
```

```{r scoring_rules}

scoring_rules <- 
  list(
    pass = list(
      pass_att = 0, pass_comp = 0, pass_inc = 0, pass_yds = 0.06667, pass_tds = 4,
      pass_int = -2, pass_40_yds = 0,  pass_300_yds = 0, pass_350_yds = 0,
      pass_400_yds = 0
    ),
    rush = list(
      all_pos = TRUE,
      rush_yds = 0.1,  rush_att = 0, rush_40_yds = 0, rush_tds = 6,
      rush_100_yds = 0, rush_150_yds = 0, rush_200_yds = 0),
    rec = list(
      all_pos = TRUE,
      rec = 0.5, rec_yds = 0.1, rec_tds = 6, rec_40_yds = 0, rec_100_yds = 0,
      rec_150_yds = 0, rec_200_yds = 0
    ),
    misc = list(
      all_pos = TRUE,
      fumbles_lost = -2, fumbles_total = 0,
      sacks = 0, two_pts = 2
    ),
    kick = list(
      xp = 1.0, fg_0019 = 1.0,  fg_2029 = 1.66667, fg_3039 = 2.33333, fg_4049 = 3.0,
      fg_50 = 4.0,  fg_miss = 0.0
    ),
    ret = list(
      all_pos = TRUE,
      return_tds = 6, return_yds = 0
    ),
    idp = list(
      all_pos = TRUE,
      idp_solo = 0, idp_asst = 0, idp_sack = 0, idp_int = 0,  idp_fum_force = 0,
      idp_fum_rec = 0,  idp_pd = 0, idp_td = 0,  idp_safety = 0
    ),
    dst = list(
      dst_fum_rec = 2,  dst_int = 2, dst_safety = 2, dst_sacks = 1, dst_td = 6,
      dst_blk = 0, dst_ret_yds = 0, dst_pts_allowed = 0
    ),
    pts_bracket = list(
      list(threshold = 0, points = 9),
      list(threshold = 6, points = 8),
      list(threshold = 13, points = 7),
      list(threshold = 20, points = 5),
      list(threshold = 27, points = 4),
      list(threshold = 34, points = 3),
      list(threshold = 99, points = 0)
    )
  )

```

```{r scrape}

scrape_file <- 
  here::here("out", paste0("scrape-", Sys.Date(), ".Rds"))

if (file.exists(scrape_file)) {
  scrape <- readRDS(scrape_file)
} else {
  scrape <- 
  scrape_data(src = c(
    "CBS", 
    "ESPN", 
    "Yahoo", 
    "NFL", 
    "FantasyPros", 
    "NumberFire", 
    "FFToday", 
    "FantasySharks", 
    "FantasyFootballNerd", 
    "Walterfootball", 
    "RTSports", 
    "FantasyData", 
    "Fleaflicker"), 
    pos = c("QB", "RB", "WR", "TE", "DST", "K"),
    season = 2021, 
    week = 0)
  
  write_rds(scrape, 
            scrape_file)
}


```

```{r dst_yardage_model}
raw_defense_performance <- 
  read_csv(here::here("in", "historicDefensePerformance.csv"),
           show_col_types = FALSE)

dst_yardage_points <-
  raw_defense_performance %>% 
    janitor::clean_names() %>% 
    rename(yards = yards_allowed) %>% 
    filter(!is.na(yards)) %>% 
    mutate(points = case_when(
      yards < 100 ~ 11.5,
      yards < 200 ~ 9.5,
      yards < 300 ~ 8.5,
      yards < 400 ~ 6,
      yards < 500 ~ 2.5,
      TRUE ~ 0
    )) %>% 
    group_by(year, team) %>% 
    summarize(weeks = n(),
              yards = sum(yards),
              points = sum(points),
              points_per_week = points / weeks,
              yards_per_week = yards / weeks)
  
model <- lm(points_per_week ~ yards_per_week,
            data=dst_yardage_points)

predicted_yards_per_game <- 
  scrape$DST %>% 
  mutate(id = if_else(
    is.na(id) & startsWith(player, "Las Vegas"),
    "0513", id)) %>% 
  filter(!is.na(dst_yds_allowed)) %>% 
  group_by(id) %>% 
  summarize(yards_per_week = mean(dst_yds_allowed) / 17)

predicted_yards_per_game$points_per_week <- 
  predict(model, predicted_yards_per_game)

predicted_yards_per_game <-
  predicted_yards_per_game %>% 
  mutate(additional_points = (points_per_week * 17) %>% round()) %>% 
  select(id, additional_points)
```

```{r projections}
#TODO evaluate projections_table.vor_baseline

projections_table <- 
  projections_table(scrape) %>% 
  add_ecr() %>% 
  add_risk() %>%
  add_adp() %>% 
  add_aav() %>% 
  add_player_info()

projections <-
  projections_table %>% 
  select(id:position, avg_type:ceiling, tier:aav) %>% 
  group_by(id, first_name, last_name, team, position) %>% 
  summarize(points = mean(points) %>% round(),
            sd_pts = mean(sd_pts) %>% round(),
            tier = min(tier),
            points_vor = mean(points_vor) %>% round(),
            floor_vor = min(floor_vor) %>% round(),
            ceiling_vor = max(ceiling_vor) %>% round(),
            pos_ecr = mean(pos_ecr) %>% round(),
            sd_ecr = mean(sd_ecr) %>% round(),
            risk = mean(risk) %>% round(),
            adp = mean(adp) %>% round(),
            aav = mean(aav) %>% round()) %>% 
  left_join(predicted_yards_per_game, by = "id") %>%
  rename(points_adjustment = additional_points) %>% 
  group_by(position) %>% 
  mutate(
    points_adjustment = if_else(
      is.na(points_adjustment), 
      0, points_adjustment),
    points = if_else(
      is.na(points_adjustment), points,
      points + points_adjustment),
    pos_rank = rank(-points, ties.method="min")) %>% 
  ungroup() %>% 
  mutate(rank = rank(-points, ties.method="min"))

# tiers are across positions - DST tiers will be off but we won't be using tiers in DST anyway

write_csv(projections, 
          here::here("out", paste0("projections-", Sys.Date(), ".csv")))
```